@echo off
rem set NLS_LANG=DANISH_DENMARK.WE8MSWIN1252
rem set NLS_LANG=DANISH_AMERICA.WE8ISO8859P15
rem set NLS_LANG=DANISH_DENMARK.AL32UTF8
set NLS_LANG=AMERICAN_AMERICA.AL32UTF8
set ORACLE_HOME=h:\apps\Oracle\oraclexe\app\oracle\product\11.2.0\server
sqlplus.exe %1