package com.geminica.adf.chapter_three.model.entity;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Mar 03 22:32:37 CET 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentEOCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentEOCollImpl() {
    }
}
