package com.geminica.adf.chapter_three.model.entity;

import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 04 21:44:48 CET 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class JobHistoryEODefImpl extends EntityDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public JobHistoryEODefImpl() {
    }
}
