package com.geminica.adf.chapter_three.model.entity;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 06 21:26:18 CET 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TestAssocEOCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public TestAssocEOCollImpl() {
    }
}
