package com.geminica.adf.chapter_two.model.service;

import oracle.jbo.*;
import oracle.jbo.client.Configuration;
import oracle.jbo.domain.*;
import oracle.jbo.domain.Number;

public class TestClient {

    public static void main(String[] args) {
        
        //type bc4jclient and Ctrl+Enter in order to have the following code generated by IDE ;)
        String amDef = "com.geminica.adf.chapter_two.model.service.HRServiceAppModule";
        String config = "HRServiceAppModuleLocal";
        ApplicationModule am = Configuration.createRootApplicationModule(amDef, config);
        ViewObject vo = am.findViewObject("DepartmentVO1");
        vo.executeQuery();
        Row deptRow = vo.first();
        
        deptRow.setAttribute("DepartmentName", "Administration");
        printRow(vo, deptRow);
        
        am.getTransaction().commit();
        
        // Work with your appmodule and view object here
        Configuration.releaseRootApplicationModule(am, true);
    }

    private static void printRow(ViewObject viewObject, Row row) {
        System.out.println(new StringBuilder("DepartmentName: ").append(row.getAttribute("DepartmentName")).toString());
    }
}
